name: 5300-env
channels:
- conda-forge
dependencies:
- python<3.10
- nb_conda_kernels
- numpy
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- ipywidgets
- nbdime
- emcee
- zeus-mcmc
- corner
- mkl-service
- jupyter_nbextensions_configurator
- pydoe
- jupyter-book
- sphinx
- ghp-import
